ALTER TABLE "SkinShopItemSettings" ADD COLUMN IF NOT EXISTS "maxSupply" INTEGER;
ALTER TABLE "SkinShopItemAudit" ADD COLUMN IF NOT EXISTS "oldMaxSupply" INTEGER;
ALTER TABLE "SkinShopItemAudit" ADD COLUMN IF NOT EXISTS "newMaxSupply" INTEGER;
