ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "totalWagerGames" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalWagerWins" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalWagerLosses" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalWagerDraws" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalWageredLamports" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalWagerWonLamports" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalWagerLostLamports" BIGINT NOT NULL DEFAULT 0;
