export { HOOKSHOT_HOOK_SOCKET_NAMES } from '@voxel-strike/shared';

export const HOOKSHOT_PRIMARY_RECOIL_DURATION_SECONDS = 0.26;
export const HOOKSHOT_PRIMARY_RECOIL_DURATION_MS = HOOKSHOT_PRIMARY_RECOIL_DURATION_SECONDS * 1000;
export const HOOKSHOT_SECONDARY_POSE_DURATION_SECONDS = 1.25;
export const HOOKSHOT_SECONDARY_POSE_DURATION_MS = HOOKSHOT_SECONDARY_POSE_DURATION_SECONDS * 1000;
