ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "totalExperience" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "GameMatchParticipant"
  ADD COLUMN IF NOT EXISTS "experienceGained" INTEGER NOT NULL DEFAULT 0;
